name: stat_reth_2
channels:
  - anaconda
  - conda-forge
  - edderic
dependencies:
  - coiled=0.0.52
  - dask=2021.8.0
  - jupyter
  - matplotlib=3.4.2
  - numpy=1.20.3
  - pandas=1.3.1
  - python=3.9.5
  - seaborn=0.11.2
  - unlikely
